set_schedule:
  name: Set A Schedule
  description: Set a schedule
  fields:
    entity_id:
      description: Name of the structure to set schedule for
      required: true
      example: "sensor.flair_structure_home"
      selector:
        entity:
          integration: flair
          domain: sensor
    schedule_name:
      description: Name of the schedule. List of available schedules can be found in the attributes of your flair structures(s).
      required: true
      example: 'Summer'
      selector:
        text:
